[tool.poetry]
name = "large language models"
version = "0.1.0"
description = "Exmaples and mini projects"
authors = ["y"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
